// <auto-generated />
using System;
using HannahElSayed0523003.DatabaseConnection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HannahElSayed0523003.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompetitionTeam", b =>
                {
                    b.Property<int>("CompetitionsCompetitionID")
                        .HasColumnType("int");

                    b.Property<int>("TeamsTeamID")
                        .HasColumnType("int");

                    b.HasKey("CompetitionsCompetitionID", "TeamsTeamID");

                    b.HasIndex("TeamsTeamID");

                    b.ToTable("CompetitionTeam");
                });

            modelBuilder.Entity("HannahElSayed0523003.Models.Coach", b =>
                {
                    b.Property<int>("CoachID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoachID"));

                    b.Property<string>("CoachName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CoachID");

                    b.ToTable("Coaches");

                    b.HasData(
                        new
                        {
                            CoachID = 1,
                            CoachName = "lama",
                            ExperienceYears = 3,
                            Specialization = "C#"
                        },
                        new
                        {
                            CoachID = 2,
                            CoachName = "salma",
                            ExperienceYears = 4,
                            Specialization = "C++"
                        },
                        new
                        {
                            CoachID = 3,
                            CoachName = "laimya",
                            ExperienceYears = 5,
                            Specialization = "F#"
                        },
                        new
                        {
                            CoachID = 4,
                            CoachName = "slama",
                            ExperienceYears = 10,
                            Specialization = "WebAPI"
                        },
                        new
                        {
                            CoachID = 5,
                            CoachName = "hanna",
                            ExperienceYears = 3,
                            Specialization = "C#"
                        });
                });

            modelBuilder.Entity("HannahElSayed0523003.Models.Competition", b =>
                {
                    b.Property<int>("CompetitionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompetitionID"));

                    b.Property<string>("CompetitionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompetitionID");

                    b.ToTable("Competitions");

                    b.HasData(
                        new
                        {
                            CompetitionID = 1,
                            CompetitionName = "app dev",
                            Date = new DateTime(2025, 10, 10, 7, 25, 1, 880, DateTimeKind.Utc).AddTicks(9952),
                            Location = "Cairo"
                        },
                        new
                        {
                            CompetitionID = 2,
                            CompetitionName = "web dev",
                            Date = new DateTime(2025, 9, 30, 7, 25, 1, 880, DateTimeKind.Utc).AddTicks(9958),
                            Location = "Giza"
                        },
                        new
                        {
                            CompetitionID = 3,
                            CompetitionName = "desktop dev",
                            Date = new DateTime(2025, 9, 20, 7, 25, 1, 880, DateTimeKind.Utc).AddTicks(9960),
                            Location = "Alexandria"
                        },
                        new
                        {
                            CompetitionID = 4,
                            CompetitionName = "mobile dev",
                            Date = new DateTime(2025, 9, 25, 7, 25, 1, 880, DateTimeKind.Utc).AddTicks(9961),
                            Location = "Giza"
                        },
                        new
                        {
                            CompetitionID = 5,
                            CompetitionName = "lol",
                            Date = new DateTime(2025, 9, 20, 7, 25, 1, 880, DateTimeKind.Utc).AddTicks(9963),
                            Location = "Cairo"
                        });
                });

            modelBuilder.Entity("HannahElSayed0523003.Models.Player", b =>
                {
                    b.Property<int>("PlayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerID"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamID")
                        .HasColumnType("int");

                    b.HasKey("PlayerID");

                    b.HasIndex("TeamID");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            PlayerID = 1,
                            Age = 17,
                            PlayerName = "ahmed",
                            Position = "leader",
                            TeamID = 1
                        },
                        new
                        {
                            PlayerID = 2,
                            Age = 18,
                            PlayerName = "mohamed",
                            Position = "member",
                            TeamID = 2
                        },
                        new
                        {
                            PlayerID = 3,
                            Age = 19,
                            PlayerName = "mahmoud",
                            Position = "leader",
                            TeamID = 3
                        },
                        new
                        {
                            PlayerID = 4,
                            Age = 15,
                            PlayerName = "salama",
                            Position = "member",
                            TeamID = 4
                        },
                        new
                        {
                            PlayerID = 5,
                            Age = 17,
                            PlayerName = "yousef",
                            Position = "member",
                            TeamID = 4
                        });
                });

            modelBuilder.Entity("HannahElSayed0523003.Models.Team", b =>
                {
                    b.Property<int>("TeamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CoachID")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TeamID");

                    b.HasIndex("CoachID")
                        .IsUnique();

                    b.HasIndex("TeamName")
                        .IsUnique();

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            TeamID = 1,
                            City = "Cairo",
                            CoachID = 1,
                            TeamName = "the wtv"
                        },
                        new
                        {
                            TeamID = 2,
                            City = "Giza",
                            CoachID = 2,
                            TeamName = "the lll"
                        },
                        new
                        {
                            TeamID = 3,
                            City = "Cairo",
                            CoachID = 3,
                            TeamName = "idk"
                        },
                        new
                        {
                            TeamID = 4,
                            City = "Alexandria",
                            CoachID = 4,
                            TeamName = "idk2"
                        },
                        new
                        {
                            TeamID = 5,
                            City = "Giza",
                            CoachID = 5,
                            TeamName = "greeners"
                        });
                });

            modelBuilder.Entity("CompetitionTeam", b =>
                {
                    b.HasOne("HannahElSayed0523003.Models.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionsCompetitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HannahElSayed0523003.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamsTeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HannahElSayed0523003.Models.Player", b =>
                {
                    b.HasOne("HannahElSayed0523003.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("HannahElSayed0523003.Models.Team", b =>
                {
                    b.HasOne("HannahElSayed0523003.Models.Coach", "coach")
                        .WithOne("Team")
                        .HasForeignKey("HannahElSayed0523003.Models.Team", "CoachID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("coach");
                });

            modelBuilder.Entity("HannahElSayed0523003.Models.Coach", b =>
                {
                    b.Navigation("Team")
                        .IsRequired();
                });

            modelBuilder.Entity("HannahElSayed0523003.Models.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
